// <auto-generated />
using System;
using Freedom.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Freedom.Infrastructure.Migrations
{
    [DbContext(typeof(FreedomDbContext))]
    [Migration("20251126013816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Freedom.Infrastructure.Data.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Listing ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Listing budget");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Listing description");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("ListingStatus")
                        .HasColumnType("int");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("Listing location address");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Listing title");

                    b.Property<string>("UploaderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Listing uploader ID");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int")
                        .HasComment("Worker ID");

                    b.Property<int>("WorkerTypeCategoryId")
                        .HasColumnType("int")
                        .HasComment("Worker type needed for job listing");

                    b.HasKey("Id");

                    b.HasIndex("UploaderId");

                    b.HasIndex("WorkerId");

                    b.HasIndex("WorkerTypeCategoryId");

                    b.ToTable("Listings", t =>
                        {
                            t.HasComment("Listings");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 1000.00m,
                            Description = "Emergency plumbing work required for burst pipe in apartment. Must arrive within 2 hours.",
                            IsApproved = false,
                            ListingStatus = 2,
                            LocationAddress = "ul. \"Tsar Osvoboditel\" 13, Sofia, Bulgaria - 1000",
                            Title = "Plumber needed ASAP for major leak",
                            UploaderId = "9a473cb5-3465-43f4-853f-ed99ae104ede",
                            WorkerId = 1,
                            WorkerTypeCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Budget = 1500.00m,
                            Description = "Need a certified electrician to inspect wiring before renovation. Not urgent yet, still planning scope.",
                            IsApproved = false,
                            ListingStatus = 5,
                            LocationAddress = "bul. \"Vitosha\" 42, Sofia, Bulgaria - 1000",
                            Title = "Electrical inspection for office space",
                            UploaderId = "e0c11f37-bf07-4b14-b022-baf80cf652a4",
                            WorkerTypeCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Budget = 600.00m,
                            Description = "Weekly maintenance: trimming hedges, mowing lawn, seasonal planting. Long-term opportunity.",
                            IsApproved = false,
                            ListingStatus = 1,
                            LocationAddress = "ul. \"Shipka\" 7, Plovdiv, Bulgaria - 4000",
                            Title = "Ongoing garden maintenance for family house",
                            UploaderId = "9a473cb5-3465-43f4-853f-ed99ae104ede",
                            WorkerTypeCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            Budget = 400.00m,
                            Description = "Apartment just renovated, need full deep clean including windows, balcony, and furniture dust removal.",
                            IsApproved = false,
                            ListingStatus = 2,
                            LocationAddress = "ul. \"Graf Ignatiev\" 19, Sofia, Bulgaria - 1000",
                            Title = "One-time deep cleaning after renovation",
                            UploaderId = "20550ad3-a8cd-439e-b6c1-96ee52f00343",
                            WorkerId = 4,
                            WorkerTypeCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            Budget = 800.00m,
                            Description = "Install new sink, toilet, and shower fixtures. Materials already purchased.",
                            IsApproved = false,
                            ListingStatus = 1,
                            LocationAddress = "ul. \"Patriarh Evtimiy\" 5, Sofia, Bulgaria - 1000",
                            Title = "Bathroom fixture installation",
                            UploaderId = "e0c11f37-bf07-4b14-b022-baf80cf652a4",
                            WorkerId = 1,
                            WorkerTypeCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Budget = 900.00m,
                            Description = "Replace old halogen lights with LED spots and improve overall lighting layout.",
                            IsApproved = false,
                            ListingStatus = 4,
                            LocationAddress = "ul. \"Rakovski\" 102, Sofia, Bulgaria - 1000",
                            Title = "Lighting upgrade for small shop",
                            UploaderId = "20550ad3-a8cd-439e-b6c1-96ee52f00343",
                            WorkerTypeCategoryId = 2
                        });
                });

            modelBuilder.Entity("Freedom.Infrastructure.Data.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Worker ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComment("Worker phone number");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Worker user ID");

                    b.Property<int>("WorkerStatus")
                        .HasColumnType("int")
                        .HasComment("Worker status");

                    b.Property<int>("WorkerTypeCategoryId")
                        .HasColumnType("int")
                        .HasComment("Worker type category ID");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasComment("Worker's years of experience");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("WorkerTypeCategoryId");

                    b.ToTable("Workers", t =>
                        {
                            t.HasComment("Workers");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PhoneNumber = "+359888111111",
                            UserId = "a3f6cd13-2457-4b58-ae29-a82f39c7fab2",
                            WorkerStatus = 0,
                            WorkerTypeCategoryId = 1,
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 2,
                            PhoneNumber = "+359888222222",
                            UserId = "6db6497d-3169-47c4-9cfd-3409e114ac73",
                            WorkerStatus = 1,
                            WorkerTypeCategoryId = 2,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            PhoneNumber = "+359888333333",
                            UserId = "c1dc1773-9c75-440a-9e98-458a48d4864a",
                            WorkerStatus = 2,
                            WorkerTypeCategoryId = 3,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 4,
                            PhoneNumber = "+359888444444",
                            UserId = "8fa9d094-d2d3-4e02-b200-63596473c5e9",
                            WorkerStatus = 0,
                            WorkerTypeCategoryId = 4,
                            YearsOfExperience = 2
                        });
                });

            modelBuilder.Entity("Freedom.Infrastructure.Data.Models.WorkerTypeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Worker Type Category ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Worker Type Category name");

                    b.HasKey("Id");

                    b.ToTable("WorkerTypeCategories", t =>
                        {
                            t.HasComment("Worker Type Categories");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Plumber"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electrician"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gardener"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cleaner"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9a473cb5-3465-43f4-853f-ed99ae104ede",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2e2e867-5fe2-498f-b177-bcc18c193d5b",
                            Email = "guest1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST1@GMAIL.COM",
                            NormalizedUserName = "GUEST1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBVRVCFNz7VV470OLDfAw4RAULWtN1AcIIXetIqhazOLakJ/+it0RJ7LKZo2tN+eEA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e573de9a-860a-4cee-8ba0-1f4660bf5b09",
                            TwoFactorEnabled = false,
                            UserName = "guest1@gmail.com"
                        },
                        new
                        {
                            Id = "e0c11f37-bf07-4b14-b022-baf80cf652a4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4020f964-9ee4-4e7b-939d-6c16b47ed052",
                            Email = "guest2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST2@GMAIL.COM",
                            NormalizedUserName = "GUEST2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECr+A1XA8Z+ggfu3y3fWBAWMX2b9icVPX7FJWbzrjyclN2cx0Qe6p33tRNPduG1dIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41eb7df6-ac73-4b7e-b519-1076a61c81de",
                            TwoFactorEnabled = false,
                            UserName = "guest2@gmail.com"
                        },
                        new
                        {
                            Id = "20550ad3-a8cd-439e-b6c1-96ee52f00343",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "135b5f06-4ffe-46b5-81ef-142e0e84065e",
                            Email = "guest3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GUEST3@GMAIL.COM",
                            NormalizedUserName = "GUEST3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC/ka6LbA/hGC487fsv3rBuWhjepkKcMPmgkfrY3D73xWhhOVEIwYo7MuUpTHNPJWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c28cff6-0560-4017-bc15-7ffb41718a8d",
                            TwoFactorEnabled = false,
                            UserName = "guest3@gmail.com"
                        },
                        new
                        {
                            Id = "a3f6cd13-2457-4b58-ae29-a82f39c7fab2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80ebff84-1752-4535-b860-d70451d47dd7",
                            Email = "plumber.worker@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "PLUMBER.WORKER@GMAIL.COM",
                            NormalizedUserName = "PLUMBER.WORKER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOj9qlgzrw7WrKdPlK8PugLFRgR9pZrf9akwv/JpBdKNWqWcpeeZx6l7JLcQCUMl2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a03c4060-f677-4c87-9bc9-f62fbb6cede4",
                            TwoFactorEnabled = false,
                            UserName = "plumber.worker@gmail.com"
                        },
                        new
                        {
                            Id = "6db6497d-3169-47c4-9cfd-3409e114ac73",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6c20665d-00ae-4a67-ae54-6be78acc776b",
                            Email = "electric.worker@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ELECTRIC.WORKER@GMAIL.COM",
                            NormalizedUserName = "ELECTRIC.WORKER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFDcWWy5bnc3G8LNVS11PTAz0CBPHstrbch9+kTr3LlXNMDTQonZ7mJWWfjhBgd5iQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "959185b0-bd68-46f4-a465-d66b58eb2737",
                            TwoFactorEnabled = false,
                            UserName = "electric.worker@gmail.com"
                        },
                        new
                        {
                            Id = "c1dc1773-9c75-440a-9e98-458a48d4864a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8e1e4b2-8617-4458-a825-57e53a74ffe3",
                            Email = "gardener.worker@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GARDENER.WORKER@GMAIL.COM",
                            NormalizedUserName = "GARDENER.WORKER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGws8tgNm3dW4zdYOYFSVpeJsafoltp5IoZP1rZd9jU6qDpyFhYOjzRgiE9em7YMXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "222f4362-f689-43db-9e0c-6f0ab98b696a",
                            TwoFactorEnabled = false,
                            UserName = "gardener.worker@gmail.com"
                        },
                        new
                        {
                            Id = "8fa9d094-d2d3-4e02-b200-63596473c5e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce25688d-8eac-4596-b191-639457abfb1b",
                            Email = "cleaner.worker@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLEANER.WORKER@GMAIL.COM",
                            NormalizedUserName = "CLEANER.WORKER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDHsSkPILk2/QB+lYmdVjdWu1X2rYvbjjHBbihFhrT90dY9xU5oFVK7JxgCpPinBzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03972e61-913a-4216-81b0-692816b4149c",
                            TwoFactorEnabled = false,
                            UserName = "cleaner.worker@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Freedom.Infrastructure.Data.Models.Listing", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freedom.Infrastructure.Data.Models.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId");

                    b.HasOne("Freedom.Infrastructure.Data.Models.WorkerTypeCategory", "WorkerTypeCategory")
                        .WithMany()
                        .HasForeignKey("WorkerTypeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uploader");

                    b.Navigation("Worker");

                    b.Navigation("WorkerTypeCategory");
                });

            modelBuilder.Entity("Freedom.Infrastructure.Data.Models.Worker", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freedom.Infrastructure.Data.Models.WorkerTypeCategory", "WorkerTypeCategory")
                        .WithMany()
                        .HasForeignKey("WorkerTypeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkerTypeCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
